workspace:
  base: /${DRONE_BRANCH%%/*}
  path: ${DRONE_BRANCH##*/}

pipeline:
  build-and-push-image:
    image: plugins/docker
    repo: fpfis/httpd-php-dev
    tags: [ 5.6 ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: release/*

